author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2024-04-13
description = Helper functions for data manipulation and analysis
tags = C13 C52
min-version = 2023b
public = head tail is_str_series nuniq nmissing shape dtypes agg
help = Datatools_help.md
sample-script = Datatools_sample.inp
